export const cityData = {
  sido: [
    {
      cityEnName: 'Daegu',
      cityCode: '27',
      cityName: '대구',
      id: 1,
    },
    {
      cityEnName: 'Seoul',
      cityCode: '11',
      cityName: '서울',
      id: 2,
    },
    {
      cityEnName: 'Busan',
      cityCode: '26',
      cityName: '부산',
      id: 3,
    },
    {
      cityEnName: 'Daejeon',
      cityCode: '30',
      cityName: '대전',
      id: 4,
    },
    {
      cityEnName: 'Incheon',
      cityCode: '28',
      cityName: '인천',
      id: 5,
    },
    {
      cityEnName: 'Gwangju',
      cityCode: '29',
      cityName: '광주',
      id: 6,
    },
    {
      cityEnName: 'Ulsan',
      cityCode: '31',
      cityName: '울산',
      id: 7,
    },
    {
      cityEnName: 'Sejong-si',
      cityCode: '36',
      cityName: '세종',
      id: 8,
    },
    {
      cityEnName: 'Gyeonggi-do',
      cityCode: '41',
      cityName: '경기도',
      id: 9,
    },
    {
      cityEnName: 'Gangwon-do',
      cityCode: '42',
      cityName: '강원도',
      id: 10,
    },
    {
      cityEnName: 'Chungcheongbuk-do',
      cityCode: '43',
      cityName: '충청북도',
      id: 11,
    },
    {
      cityEnName: 'Chungcheongnam-do',
      cityCode: '44',
      cityName: '충청남도',
      id: 12,
    },
    {
      cityEnName: 'Jeollabuk-do',
      cityCode: '45',
      cityName: '전라북도',
      id: 13,
    },
    {
      cityEnName: 'Jellanam-do',
      cityCode: '46',
      cityName: '전라남도',
      id: 14,
    },
    {
      cityEnName: 'Gyeongsangbuk-do',
      cityCode: '47',
      cityName: '경상북도',
      id: 15,
    },
    {
      cityEnName: 'Gyeongsangnam-do',
      cityCode: '48',
      cityName: '경상남도',
      id: 16,
    },
    {
      cityEnName: 'Jeju-do',
      cityCode: '50',
      cityName: '제주도',
      id: 17,
    },
  ],
  gugun: [
    {
      gugunCode: '11260',
      gugunEngName: 'Jungnang-gu',
      fullName: '서울특별시 중랑구',
      gugunKorName: '중랑구',
      cityCode: '11',
      id: 1,
    },
    {
      gugunCode: '11110',
      gugunEngName: 'Jongno-gu',
      fullName: '서울특별시 종로구',
      gugunKorName: '종로구',
      cityCode: '11',
      id: 2,
    },
    {
      gugunCode: '11290',
      gugunEngName: 'Seongbuk-gu',
      fullName: '서울특별시 성북구',
      gugunKorName: '성북구',
      cityCode: '11',
      id: 3,
    },
    {
      gugunCode: '11305',
      gugunEngName: 'Gangbuk-gu',
      fullName: '서울특별시 강북구',
      gugunKorName: '강북구',
      cityCode: '11',
      id: 4,
    },
    {
      gugunCode: '11320',
      gugunEngName: 'Dobong-gu',
      fullName: '서울특별시 도봉구',
      gugunKorName: '도봉구',
      cityCode: '11',
      id: 5,
    },
    {
      gugunCode: '11350',
      gugunEngName: 'Nowon-gu',
      fullName: '서울특별시 노원구',
      gugunKorName: '노원구',
      cityCode: '11',
      id: 6,
    },
    {
      gugunCode: '11380',
      gugunEngName: 'Eunpyeong-gu',
      fullName: '서울특별시 은평구',
      gugunKorName: '은평구',
      cityCode: '11',
      id: 7,
    },
    {
      gugunCode: '11170',
      gugunEngName: 'Yongsan-gu',
      fullName: '서울특별시 용산구',
      gugunKorName: '용산구',
      cityCode: '11',
      id: 8,
    },
    {
      gugunCode: '11410',
      gugunEngName: 'Seodaemun-gu',
      fullName: '서울특별시 서대문구',
      gugunKorName: '서대문구',
      cityCode: '11',
      id: 9,
    },
    {
      gugunCode: '11140',
      gugunEngName: 'Jung-gu',
      fullName: '서울특별시 중구',
      gugunKorName: '중구',
      cityCode: '11',
      id: 10,
    },
    {
      gugunCode: '11440',
      gugunEngName: 'Mapo-gu',
      fullName: '서울특별시 마포구',
      gugunKorName: '마포구',
      cityCode: '11',
      id: 11,
    },
    {
      gugunCode: '11200',
      gugunEngName: 'Seongdong-gu',
      fullName: '서울특별시 성동구',
      gugunKorName: '성동구',
      cityCode: '11',
      id: 12,
    },
    {
      gugunCode: '11470',
      gugunEngName: 'Yangcheon-gu',
      fullName: '서울특별시 양천구',
      gugunKorName: '양천구',
      cityCode: '11',
      id: 13,
    },
    {
      gugunCode: '11500',
      gugunEngName: 'Gangseo-gu',
      fullName: '서울특별시 강서구',
      gugunKorName: '강서구',
      cityCode: '11',
      id: 14,
    },
    {
      gugunCode: '11530',
      gugunEngName: 'Guro-gu',
      fullName: '서울특별시 구로구',
      gugunKorName: '구로구',
      cityCode: '11',
      id: 15,
    },
    {
      gugunCode: '11545',
      gugunEngName: 'Geumcheon-gu',
      fullName: '서울특별시 금천구',
      gugunKorName: '금천구',
      cityCode: '11',
      id: 16,
    },
    {
      gugunCode: '11560',
      gugunEngName: 'Yeongdeungpo-gu',
      fullName: '서울특별시 영등포구',
      gugunKorName: '영등포구',
      cityCode: '11',
      id: 17,
    },
    {
      gugunCode: '11590',
      gugunEngName: 'Dongjak-gu',
      fullName: '서울특별시 동작구',
      gugunKorName: '동작구',
      cityCode: '11',
      id: 18,
    },
    {
      gugunCode: '11620',
      gugunEngName: 'Gwanak-gu',
      fullName: '서울특별시 관악구',
      gugunKorName: '관악구',
      cityCode: '11',
      id: 19,
    },
    {
      gugunCode: '11650',
      gugunEngName: 'Seocho-gu',
      fullName: '서울특별시 서초구',
      gugunKorName: '서초구',
      cityCode: '11',
      id: 20,
    },
    {
      gugunCode: '11680',
      gugunEngName: 'Gangnam-gu',
      fullName: '서울특별시 강남구',
      gugunKorName: '강남구',
      cityCode: '11',
      id: 21,
    },
    {
      gugunCode: '11215',
      gugunEngName: 'Gwangjin-gu',
      fullName: '서울특별시 광진구',
      gugunKorName: '광진구',
      cityCode: '11',
      id: 22,
    },
    {
      gugunCode: '11710',
      gugunEngName: 'Songpa-gu',
      fullName: '서울특별시 송파구',
      gugunKorName: '송파구',
      cityCode: '11',
      id: 23,
    },
    {
      gugunCode: '11740',
      gugunEngName: 'Gangdong-gu',
      fullName: '서울특별시 강동구',
      gugunKorName: '강동구',
      cityCode: '11',
      id: 24,
    },
    {
      gugunCode: '11230',
      gugunEngName: 'Dongdaemun-gu',
      fullName: '서울특별시 동대문구',
      gugunKorName: '동대문구',
      cityCode: '11',
      id: 25,
    },
    {
      gugunCode: '26110',
      gugunEngName: 'Jung-gu',
      fullName: '부산광역시 중구',
      gugunKorName: '중구',
      cityCode: '26',
      id: 26,
    },
    {
      gugunCode: '26410',
      gugunEngName: 'Geumjeong-gu',
      fullName: '부산광역시 금정구',
      gugunKorName: '금정구',
      cityCode: '26',
      id: 27,
    },
    {
      gugunCode: '26500',
      gugunEngName: 'Suyeong-gu',
      fullName: '부산광역시 수영구',
      gugunKorName: '수영구',
      cityCode: '26',
      id: 28,
    },
    {
      gugunCode: '26140',
      gugunEngName: 'Seo-gu',
      fullName: '부산광역시 서구',
      gugunKorName: '서구',
      cityCode: '26',
      id: 29,
    },
    {
      gugunCode: '26440',
      gugunEngName: 'Gangseo-gu',
      fullName: '부산광역시 강서구',
      gugunKorName: '강서구',
      cityCode: '26',
      id: 30,
    },
    {
      gugunCode: '26470',
      gugunEngName: 'Yeonje-gu',
      fullName: '부산광역시 연제구',
      gugunKorName: '연제구',
      cityCode: '26',
      id: 31,
    },
    {
      gugunCode: '26530',
      gugunEngName: 'Sasang-gu',
      fullName: '부산광역시 사상구',
      gugunKorName: '사상구',
      cityCode: '26',
      id: 32,
    },
    {
      gugunCode: '26710',
      gugunEngName: 'Gijang-gun',
      fullName: '부산광역시 기장군',
      gugunKorName: '기장군',
      cityCode: '26',
      id: 33,
    },
    {
      gugunCode: '26290',
      gugunEngName: 'Nam-gu',
      fullName: '부산광역시 남구',
      gugunKorName: '남구',
      cityCode: '26',
      id: 34,
    },
    {
      gugunCode: '26170',
      gugunEngName: 'Dong-gu',
      fullName: '부산광역시 동구',
      gugunKorName: '동구',
      cityCode: '26',
      id: 35,
    },
    {
      gugunCode: '26200',
      gugunEngName: 'Yeongdo-gu',
      fullName: '부산광역시 영도구',
      gugunKorName: '영도구',
      cityCode: '26',
      id: 36,
    },
    {
      gugunCode: '26230',
      gugunEngName: 'Busanjin-gu',
      fullName: '부산광역시 부산진구',
      gugunKorName: '부산진구',
      cityCode: '26',
      id: 37,
    },
    {
      gugunCode: '26320',
      gugunEngName: 'Buk-gu',
      fullName: '부산광역시 북구',
      gugunKorName: '북구',
      cityCode: '26',
      id: 38,
    },
    {
      gugunCode: '26260',
      gugunEngName: 'Dongnae-gu',
      fullName: '부산광역시 동래구',
      gugunKorName: '동래구',
      cityCode: '26',
      id: 39,
    },
    {
      gugunCode: '26350',
      gugunEngName: 'Haeundae-gu',
      fullName: '부산광역시 해운대구',
      gugunKorName: '해운대구',
      cityCode: '26',
      id: 40,
    },
    {
      gugunCode: '26380',
      gugunEngName: 'Saha-gu',
      fullName: '부산광역시 사하구',
      gugunKorName: '사하구',
      cityCode: '26',
      id: 41,
    },
    {
      gugunCode: '27140',
      gugunEngName: 'Dong-gu',
      fullName: '대구광역시 동구',
      gugunKorName: '동구',
      cityCode: '27',
      id: 42,
    },
    {
      gugunCode: '27170',
      gugunEngName: 'Seo-gu',
      fullName: '대구광역시 서구',
      gugunKorName: '서구',
      cityCode: '27',
      id: 43,
    },
    {
      gugunCode: '27290',
      gugunEngName: 'Dalseo-gu',
      fullName: '대구광역시 달서구',
      gugunKorName: '달서구',
      cityCode: '27',
      id: 44,
    },
    {
      gugunCode: '27110',
      gugunEngName: 'Jung-gu',
      fullName: '대구광역시 중구',
      gugunKorName: '중구',
      cityCode: '27',
      id: 45,
    },
    {
      gugunCode: '27230',
      gugunEngName: 'Buk-gu',
      fullName: '대구광역시 북구',
      gugunKorName: '북구',
      cityCode: '27',
      id: 46,
    },
    {
      gugunCode: '27200',
      gugunEngName: 'Nam-gu',
      fullName: '대구광역시 남구',
      gugunKorName: '남구',
      cityCode: '27',
      id: 47,
    },
    {
      gugunCode: '27260',
      gugunEngName: 'Suseong-gu',
      fullName: '대구광역시 수성구',
      gugunKorName: '수성구',
      cityCode: '27',
      id: 48,
    },
    {
      gugunCode: '27710',
      gugunEngName: 'Dalseong-gun',
      fullName: '대구광역시 달성군',
      gugunKorName: '달성군',
      cityCode: '27',
      id: 49,
    },
    {
      gugunCode: '28140',
      gugunEngName: 'Dong-gu',
      fullName: '인천광역시 동구',
      gugunKorName: '동구',
      cityCode: '28',
      id: 50,
    },
    {
      gugunCode: '28237',
      gugunEngName: 'Bupyeong-gu',
      fullName: '인천광역시 부평구',
      gugunKorName: '부평구',
      cityCode: '28',
      id: 51,
    },
    {
      gugunCode: '28110',
      gugunEngName: 'Jung-gu',
      fullName: '인천광역시 중구',
      gugunKorName: '중구',
      cityCode: '28',
      id: 52,
    },
    {
      gugunCode: '28720',
      gugunEngName: 'Ongjin-gun',
      fullName: '인천광역시 옹진군',
      gugunKorName: '옹진군',
      cityCode: '28',
      id: 53,
    },
    {
      gugunCode: '28177',
      gugunEngName: 'Michuhol-gu',
      fullName: '인천광역시 미추홀구',
      gugunKorName: '미추홀구',
      cityCode: '28',
      id: 54,
    },
    {
      gugunCode: '28185',
      gugunEngName: 'Yeonsu-gu',
      fullName: '인천광역시 연수구',
      gugunKorName: '연수구',
      cityCode: '28',
      id: 55,
    },
    {
      gugunCode: '28710',
      gugunEngName: 'Ganghwa-gun',
      fullName: '인천광역시 강화군',
      gugunKorName: '강화군',
      cityCode: '28',
      id: 56,
    },
    {
      gugunCode: '28260',
      gugunEngName: 'Seo-gu',
      fullName: '인천광역시 서구',
      gugunKorName: '서구',
      cityCode: '28',
      id: 57,
    },
    {
      gugunCode: '28200',
      gugunEngName: 'Namdong-gu',
      fullName: '인천광역시 남동구',
      gugunKorName: '남동구',
      cityCode: '28',
      id: 58,
    },
    {
      gugunCode: '28245',
      gugunEngName: 'Gyeyang-gu',
      fullName: '인천광역시 계양구',
      gugunKorName: '계양구',
      cityCode: '28',
      id: 59,
    },
    {
      gugunCode: '29110',
      gugunEngName: 'Dong-gu',
      fullName: '광주광역시 동구',
      gugunKorName: '동구',
      cityCode: '29',
      id: 60,
    },
    {
      gugunCode: '29140',
      gugunEngName: 'Seo-gu',
      fullName: '광주광역시 서구',
      gugunKorName: '서구',
      cityCode: '29',
      id: 61,
    },
    {
      gugunCode: '29155',
      gugunEngName: 'Nam-gu',
      fullName: '광주광역시 남구',
      gugunKorName: '남구',
      cityCode: '29',
      id: 62,
    },
    {
      gugunCode: '29170',
      gugunEngName: 'Buk-gu',
      fullName: '광주광역시 북구',
      gugunKorName: '북구',
      cityCode: '29',
      id: 63,
    },
    {
      gugunCode: '29200',
      gugunEngName: 'Gwangsan-gu',
      fullName: '광주광역시 광산구',
      gugunKorName: '광산구',
      cityCode: '29',
      id: 64,
    },
    {
      gugunCode: '30110',
      gugunEngName: 'Dong-gu',
      fullName: '대전광역시 동구',
      gugunKorName: '동구',
      cityCode: '30',
      id: 65,
    },
    {
      gugunCode: '30140',
      gugunEngName: 'Jung-gu',
      fullName: '대전광역시 중구',
      gugunKorName: '중구',
      cityCode: '30',
      id: 66,
    },
    {
      gugunCode: '30200',
      gugunEngName: 'Yuseong-gu',
      fullName: '대전광역시 유성구',
      gugunKorName: '유성구',
      cityCode: '30',
      id: 67,
    },
    {
      gugunCode: '30170',
      gugunEngName: 'Seo-gu',
      fullName: '대전광역시 서구',
      gugunKorName: '서구',
      cityCode: '30',
      id: 68,
    },
    {
      gugunCode: '30230',
      gugunEngName: 'Daedeok-gu',
      fullName: '대전광역시 대덕구',
      gugunKorName: '대덕구',
      cityCode: '30',
      id: 69,
    },
    {
      gugunCode: '31110',
      gugunEngName: 'Jung-gu',
      fullName: '울산광역시 중구',
      gugunKorName: '중구',
      cityCode: '31',
      id: 70,
    },
    {
      gugunCode: '31140',
      gugunEngName: 'Nam-gu',
      fullName: '울산광역시 남구',
      gugunKorName: '남구',
      cityCode: '31',
      id: 71,
    },
    {
      gugunCode: '31170',
      gugunEngName: 'Dong-gu',
      fullName: '울산광역시 동구',
      gugunKorName: '동구',
      cityCode: '31',
      id: 72,
    },
    {
      gugunCode: '31200',
      gugunEngName: 'Buk-gu',
      fullName: '울산광역시 북구',
      gugunKorName: '북구',
      cityCode: '31',
      id: 73,
    },
    {
      gugunCode: '31710',
      gugunEngName: 'Ulju-gun',
      fullName: '울산광역시 울주군',
      gugunKorName: '울주군',
      cityCode: '31',
      id: 74,
    },
    {
      gugunCode: '36110',
      gugunEngName: 'Sejong-si',
      fullName: '세종특별자치시',
      gugunKorName: '세종특별자치시',
      cityCode: '36',
      id: 75,
    },
    {
      gugunCode: '41111',
      gugunEngName: 'Jangan-gu, Suwon-si',
      fullName: '경기도 수원시 장안구',
      gugunKorName: '수원시 장안구',
      cityCode: '41',
      id: 76,
    },
    {
      gugunCode: '41273',
      gugunEngName: 'Danwon-gu, Ansan-si',
      fullName: '경기도 안산시 단원구',
      gugunKorName: '안산시 단원구',
      cityCode: '41',
      id: 77,
    },
    {
      gugunCode: '41281',
      gugunEngName: 'Deogyang-gu, Goyang-si',
      fullName: '경기도 고양시 덕양구',
      gugunKorName: '고양시 덕양구',
      cityCode: '41',
      id: 78,
    },
    {
      gugunCode: '41285',
      gugunEngName: 'Ilsandong-gu, Goyang-si',
      fullName: '경기도 고양시 일산동구',
      gugunKorName: '고양시 일산동구',
      cityCode: '41',
      id: 79,
    },
    {
      gugunCode: '41287',
      gugunEngName: 'Ilsanseo-gu, Goyang-si',
      fullName: '경기도 고양시 일산서구',
      gugunKorName: '고양시 일산서구',
      cityCode: '41',
      id: 80,
    },
    {
      gugunCode: '41113',
      gugunEngName: 'Gwonseon-gu, Suwon-si',
      fullName: '경기도 수원시 권선구',
      gugunKorName: '수원시 권선구',
      cityCode: '41',
      id: 81,
    },
    {
      gugunCode: '41290',
      gugunEngName: 'Gwacheon-si',
      fullName: '경기도 과천시',
      gugunKorName: '과천시',
      cityCode: '41',
      id: 82,
    },
    {
      gugunCode: '41115',
      gugunEngName: 'Paldal-gu, Suwon-si',
      fullName: '경기도 수원시 팔달구',
      gugunKorName: '수원시 팔달구',
      cityCode: '41',
      id: 83,
    },
    {
      gugunCode: '41310',
      gugunEngName: 'Guri-si',
      fullName: '경기도 구리시',
      gugunKorName: '구리시',
      cityCode: '41',
      id: 84,
    },
    {
      gugunCode: '41360',
      gugunEngName: 'Namyangju-si',
      fullName: '경기도 남양주시',
      gugunKorName: '남양주시',
      cityCode: '41',
      id: 85,
    },
    {
      gugunCode: '41117',
      gugunEngName: 'Yeongtong-gu, Suwon-si',
      fullName: '경기도 수원시 영통구',
      gugunKorName: '수원시 영통구',
      cityCode: '41',
      id: 86,
    },
    {
      gugunCode: '41370',
      gugunEngName: 'Osan-si',
      fullName: '경기도 오산시',
      gugunKorName: '오산시',
      cityCode: '41',
      id: 87,
    },
    {
      gugunCode: '41390',
      gugunEngName: 'Siheung-si',
      fullName: '경기도 시흥시',
      gugunKorName: '시흥시',
      cityCode: '41',
      id: 88,
    },
    {
      gugunCode: '41410',
      gugunEngName: 'Gunpo-si',
      fullName: '경기도 군포시',
      gugunKorName: '군포시',
      cityCode: '41',
      id: 89,
    },
    {
      gugunCode: '41430',
      gugunEngName: 'Uiwang-si',
      fullName: '경기도 의왕시',
      gugunKorName: '의왕시',
      cityCode: '41',
      id: 90,
    },
    {
      gugunCode: '41450',
      gugunEngName: 'Hanam-si',
      fullName: '경기도 하남시',
      gugunKorName: '하남시',
      cityCode: '41',
      id: 91,
    },
    {
      gugunCode: '41461',
      gugunEngName: 'Cheoin-gu, Yongin-si',
      fullName: '경기도 용인시 처인구',
      gugunKorName: '용인시 처인구',
      cityCode: '41',
      id: 92,
    },
    {
      gugunCode: '41463',
      gugunEngName: 'Giheung-gu, Yongin-si',
      fullName: '경기도 용인시 기흥구',
      gugunKorName: '용인시 기흥구',
      cityCode: '41',
      id: 93,
    },
    {
      gugunCode: '41131',
      gugunEngName: 'Sujeong-gu, Seongnam-si',
      fullName: '경기도 성남시 수정구',
      gugunKorName: '성남시 수정구',
      cityCode: '41',
      id: 94,
    },
    {
      gugunCode: '41133',
      gugunEngName: 'Jungwon-gu, Seongnam-si',
      fullName: '경기도 성남시 중원구',
      gugunKorName: '성남시 중원구',
      cityCode: '41',
      id: 95,
    },
    {
      gugunCode: '41465',
      gugunEngName: 'Suji-gu, Yongin-si',
      fullName: '경기도 용인시 수지구',
      gugunKorName: '용인시 수지구',
      cityCode: '41',
      id: 96,
    },
    {
      gugunCode: '41171',
      gugunEngName: 'Manan-gu, Anyang-si',
      fullName: '경기도 안양시 만안구',
      gugunKorName: '안양시 만안구',
      cityCode: '41',
      id: 97,
    },
    {
      gugunCode: '41135',
      gugunEngName: 'Bundang-gu, Seongnam-si',
      fullName: '경기도 성남시 분당구',
      gugunKorName: '성남시 분당구',
      cityCode: '41',
      id: 98,
    },
    {
      gugunCode: '41150',
      gugunEngName: 'Uijeongbu-si',
      fullName: '경기도 의정부시',
      gugunKorName: '의정부시',
      cityCode: '41',
      id: 99,
    },
    {
      gugunCode: '41480',
      gugunEngName: 'Paju-si',
      fullName: '경기도 파주시',
      gugunKorName: '파주시',
      cityCode: '41',
      id: 100,
    },
    {
      gugunCode: '41500',
      gugunEngName: 'Icheon-si',
      fullName: '경기도 이천시',
      gugunKorName: '이천시',
      cityCode: '41',
      id: 101,
    },
    {
      gugunCode: '41550',
      gugunEngName: 'Anseong-si',
      fullName: '경기도 안성시',
      gugunKorName: '안성시',
      cityCode: '41',
      id: 102,
    },
    {
      gugunCode: '41570',
      gugunEngName: 'Gimpo-si',
      fullName: '경기도 김포시',
      gugunKorName: '김포시',
      cityCode: '41',
      id: 103,
    },
    {
      gugunCode: '41590',
      gugunEngName: 'Hwaseong-si',
      fullName: '경기도 화성시',
      gugunKorName: '화성시',
      cityCode: '41',
      id: 104,
    },
    {
      gugunCode: '41173',
      gugunEngName: 'Dongan-gu, Anyang-si',
      fullName: '경기도 안양시 동안구',
      gugunKorName: '안양시 동안구',
      cityCode: '41',
      id: 105,
    },
    {
      gugunCode: '41610',
      gugunEngName: 'Gwangju-si',
      fullName: '경기도 광주시',
      gugunKorName: '광주시',
      cityCode: '41',
      id: 106,
    },
    {
      gugunCode: '41630',
      gugunEngName: 'Yangju-si',
      fullName: '경기도 양주시',
      gugunKorName: '양주시',
      cityCode: '41',
      id: 107,
    },
    {
      gugunCode: '41650',
      gugunEngName: 'Pocheon-si',
      fullName: '경기도 포천시',
      gugunKorName: '포천시',
      cityCode: '41',
      id: 108,
    },
    {
      gugunCode: '41670',
      gugunEngName: 'Yeoju-si',
      fullName: '경기도 여주시',
      gugunKorName: '여주시',
      cityCode: '41',
      id: 109,
    },
    {
      gugunCode: '41190',
      gugunEngName: 'Bucheon-si',
      fullName: '경기도 부천시',
      gugunKorName: '부천시',
      cityCode: '41',
      id: 110,
    },
    {
      gugunCode: '41800',
      gugunEngName: 'Yeoncheon-gun',
      fullName: '경기도 연천군',
      gugunKorName: '연천군',
      cityCode: '41',
      id: 111,
    },
    {
      gugunCode: '41820',
      gugunEngName: 'Gapyeong-gun',
      fullName: '경기도 가평군',
      gugunKorName: '가평군',
      cityCode: '41',
      id: 112,
    },
    {
      gugunCode: '41830',
      gugunEngName: 'Yangpyeong-gun',
      fullName: '경기도 양평군',
      gugunKorName: '양평군',
      cityCode: '41',
      id: 113,
    },
    {
      gugunCode: '41210',
      gugunEngName: 'Gwangmyeong-si',
      fullName: '경기도 광명시',
      gugunKorName: '광명시',
      cityCode: '41',
      id: 114,
    },
    {
      gugunCode: '41220',
      gugunEngName: 'Pyeongtaek-si',
      fullName: '경기도 평택시',
      gugunKorName: '평택시',
      cityCode: '41',
      id: 115,
    },
    {
      gugunCode: '41250',
      gugunEngName: 'Dongducheon-si',
      fullName: '경기도 동두천시',
      gugunKorName: '동두천시',
      cityCode: '41',
      id: 116,
    },
    {
      gugunCode: '41271',
      gugunEngName: 'Sangnok-gu, Ansan-si',
      fullName: '경기도 안산시 상록구',
      gugunKorName: '안산시 상록구',
      cityCode: '41',
      id: 117,
    },
    {
      gugunCode: '42110',
      gugunEngName: 'Chuncheon-si',
      fullName: '강원도 춘천시',
      gugunKorName: '춘천시',
      cityCode: '42',
      id: 118,
    },
    {
      gugunCode: '42130',
      gugunEngName: 'Wonju-si',
      fullName: '강원도 원주시',
      gugunKorName: '원주시',
      cityCode: '42',
      id: 119,
    },
    {
      gugunCode: '42150',
      gugunEngName: 'Gangneung-si',
      fullName: '강원도 강릉시',
      gugunKorName: '강릉시',
      cityCode: '42',
      id: 120,
    },
    {
      gugunCode: '42230',
      gugunEngName: 'Samcheok-si',
      fullName: '강원도 삼척시',
      gugunKorName: '삼척시',
      cityCode: '42',
      id: 121,
    },
    {
      gugunCode: '42170',
      gugunEngName: 'Donghae-si',
      fullName: '강원도 동해시',
      gugunKorName: '동해시',
      cityCode: '42',
      id: 122,
    },
    {
      gugunCode: '42190',
      gugunEngName: 'Taebaek-si',
      fullName: '강원도 태백시',
      gugunKorName: '태백시',
      cityCode: '42',
      id: 123,
    },
    {
      gugunCode: '42210',
      gugunEngName: 'Sokcho-si',
      fullName: '강원도 속초시',
      gugunKorName: '속초시',
      cityCode: '42',
      id: 124,
    },
    {
      gugunCode: '42720',
      gugunEngName: 'Hongcheon-gun',
      fullName: '강원도 홍천군',
      gugunKorName: '홍천군',
      cityCode: '42',
      id: 125,
    },
    {
      gugunCode: '42730',
      gugunEngName: 'Hoengseong-gun',
      fullName: '강원도 횡성군',
      gugunKorName: '횡성군',
      cityCode: '42',
      id: 126,
    },
    {
      gugunCode: '42750',
      gugunEngName: 'Yeongwol-gun',
      fullName: '강원도 영월군',
      gugunKorName: '영월군',
      cityCode: '42',
      id: 127,
    },
    {
      gugunCode: '42760',
      gugunEngName: 'Pyeongchang-gun',
      fullName: '강원도 평창군',
      gugunKorName: '평창군',
      cityCode: '42',
      id: 128,
    },
    {
      gugunCode: '42770',
      gugunEngName: 'Jeongseon-gun',
      fullName: '강원도 정선군',
      gugunKorName: '정선군',
      cityCode: '42',
      id: 129,
    },
    {
      gugunCode: '42780',
      gugunEngName: 'Cheorwon-gun',
      fullName: '강원도 철원군',
      gugunKorName: '철원군',
      cityCode: '42',
      id: 130,
    },
    {
      gugunCode: '42790',
      gugunEngName: 'Hwacheon-gun',
      fullName: '강원도 화천군',
      gugunKorName: '화천군',
      cityCode: '42',
      id: 131,
    },
    {
      gugunCode: '42800',
      gugunEngName: 'Yanggu-gun',
      fullName: '강원도 양구군',
      gugunKorName: '양구군',
      cityCode: '42',
      id: 132,
    },
    {
      gugunCode: '42810',
      gugunEngName: 'Inje-gun',
      fullName: '강원도 인제군',
      gugunKorName: '인제군',
      cityCode: '42',
      id: 133,
    },
    {
      gugunCode: '42820',
      gugunEngName: 'Goseong-gun',
      fullName: '강원도 고성군',
      gugunKorName: '고성군',
      cityCode: '42',
      id: 134,
    },
    {
      gugunCode: '42830',
      gugunEngName: 'Yangyang-gun',
      fullName: '강원도 양양군',
      gugunKorName: '양양군',
      cityCode: '42',
      id: 135,
    },
    {
      gugunCode: '43750',
      gugunEngName: 'Jincheon-gun',
      fullName: '충청북도 진천군',
      gugunKorName: '진천군',
      cityCode: '43',
      id: 136,
    },
    {
      gugunCode: '43760',
      gugunEngName: 'Goesan-gun',
      fullName: '충청북도 괴산군',
      gugunKorName: '괴산군',
      cityCode: '43',
      id: 137,
    },
    {
      gugunCode: '43111',
      gugunEngName: 'Sangdang-gu, Cheongju-si',
      fullName: '충청북도 청주시 상당구',
      gugunKorName: '청주시 상당구',
      cityCode: '43',
      id: 138,
    },
    {
      gugunCode: '43740',
      gugunEngName: 'Yeongdong-gun',
      fullName: '충청북도 영동군',
      gugunKorName: '영동군',
      cityCode: '43',
      id: 139,
    },
    {
      gugunCode: '43745',
      gugunEngName: 'Jeungpyeong-gun',
      fullName: '충청북도 증평군',
      gugunKorName: '증평군',
      cityCode: '43',
      id: 140,
    },
    {
      gugunCode: '43112',
      gugunEngName: 'Seowon-gu, Cheongju-si',
      fullName: '충청북도 청주시 서원구',
      gugunKorName: '청주시 서원구',
      cityCode: '43',
      id: 141,
    },
    {
      gugunCode: '43770',
      gugunEngName: 'Eumseong-gun',
      fullName: '충청북도 음성군',
      gugunKorName: '음성군',
      cityCode: '43',
      id: 142,
    },
    {
      gugunCode: '43800',
      gugunEngName: 'Danyang-gun',
      fullName: '충청북도 단양군',
      gugunKorName: '단양군',
      cityCode: '43',
      id: 143,
    },
    {
      gugunCode: '43113',
      gugunEngName: 'Heungdeok-gu, Cheongju-si',
      fullName: '충청북도 청주시 흥덕구',
      gugunKorName: '청주시 흥덕구',
      cityCode: '43',
      id: 144,
    },
    {
      gugunCode: '43114',
      gugunEngName: 'Cheongwon-gu, Cheongju-si',
      fullName: '충청북도 청주시 청원구',
      gugunKorName: '청주시 청원구',
      cityCode: '43',
      id: 145,
    },
    {
      gugunCode: '43130',
      gugunEngName: 'Chungju-si',
      fullName: '충청북도 충주시',
      gugunKorName: '충주시',
      cityCode: '43',
      id: 146,
    },
    {
      gugunCode: '43720',
      gugunEngName: 'Boeun-gun',
      fullName: '충청북도 보은군',
      gugunKorName: '보은군',
      cityCode: '43',
      id: 147,
    },
    {
      gugunCode: '43730',
      gugunEngName: 'Okcheon-gun',
      fullName: '충청북도 옥천군',
      gugunKorName: '옥천군',
      cityCode: '43',
      id: 148,
    },
    {
      gugunCode: '43150',
      gugunEngName: 'Jecheon-si',
      fullName: '충청북도 제천시',
      gugunKorName: '제천시',
      cityCode: '43',
      id: 149,
    },
    {
      gugunCode: '44131',
      gugunEngName: 'Dongnam-gu, Cheonan-si',
      fullName: '충청남도 천안시 동남구',
      gugunKorName: '천안시 동남구',
      cityCode: '44',
      id: 150,
    },
    {
      gugunCode: '44800',
      gugunEngName: 'Hongseong-gun',
      fullName: '충청남도 홍성군',
      gugunKorName: '홍성군',
      cityCode: '44',
      id: 151,
    },
    {
      gugunCode: '44810',
      gugunEngName: 'Yesan-gun',
      fullName: '충청남도 예산군',
      gugunKorName: '예산군',
      cityCode: '44',
      id: 152,
    },
    {
      gugunCode: '44150',
      gugunEngName: 'Gongju-si',
      fullName: '충청남도 공주시',
      gugunKorName: '공주시',
      cityCode: '44',
      id: 153,
    },
    {
      gugunCode: '44133',
      gugunEngName: 'Seobuk-gu, Cheonan-si',
      fullName: '충청남도 천안시 서북구',
      gugunKorName: '천안시 서북구',
      cityCode: '44',
      id: 154,
    },
    {
      gugunCode: '44825',
      gugunEngName: 'Taean-gun',
      fullName: '충청남도 태안군',
      gugunKorName: '태안군',
      cityCode: '44',
      id: 155,
    },
    {
      gugunCode: '44180',
      gugunEngName: 'Boryeong-si',
      fullName: '충청남도 보령시',
      gugunKorName: '보령시',
      cityCode: '44',
      id: 156,
    },
    {
      gugunCode: '44230',
      gugunEngName: 'Nonsan-si',
      fullName: '충청남도 논산시',
      gugunKorName: '논산시',
      cityCode: '44',
      id: 157,
    },
    {
      gugunCode: '44250',
      gugunEngName: 'Gyeryong-si',
      fullName: '충청남도 계룡시',
      gugunKorName: '계룡시',
      cityCode: '44',
      id: 158,
    },
    {
      gugunCode: '44200',
      gugunEngName: 'Asan-si',
      fullName: '충청남도 아산시',
      gugunKorName: '아산시',
      cityCode: '44',
      id: 159,
    },
    {
      gugunCode: '44210',
      gugunEngName: 'Seosan-si',
      fullName: '충청남도 서산시',
      gugunKorName: '서산시',
      cityCode: '44',
      id: 160,
    },
    {
      gugunCode: '44270',
      gugunEngName: 'Dangjin-si',
      fullName: '충청남도 당진시',
      gugunKorName: '당진시',
      cityCode: '44',
      id: 161,
    },
    {
      gugunCode: '44710',
      gugunEngName: 'Geumsan-gun',
      fullName: '충청남도 금산군',
      gugunKorName: '금산군',
      cityCode: '44',
      id: 162,
    },
    {
      gugunCode: '44760',
      gugunEngName: 'Buyeo-gun',
      fullName: '충청남도 부여군',
      gugunKorName: '부여군',
      cityCode: '44',
      id: 163,
    },
    {
      gugunCode: '44770',
      gugunEngName: 'Seocheon-gun',
      fullName: '충청남도 서천군',
      gugunKorName: '서천군',
      cityCode: '44',
      id: 164,
    },
    {
      gugunCode: '44790',
      gugunEngName: 'Cheongyang-gun',
      fullName: '충청남도 청양군',
      gugunKorName: '청양군',
      cityCode: '44',
      id: 165,
    },
    {
      gugunCode: '45111',
      gugunEngName: 'Wansan-gu, Jeonju-si',
      fullName: '전라북도 전주시 완산구',
      gugunKorName: '전주시 완산구',
      cityCode: '45',
      id: 166,
    },
    {
      gugunCode: '45750',
      gugunEngName: 'Imsil-gun',
      fullName: '전라북도 임실군',
      gugunKorName: '임실군',
      cityCode: '45',
      id: 167,
    },
    {
      gugunCode: '45770',
      gugunEngName: 'Sunchang-gun',
      fullName: '전라북도 순창군',
      gugunKorName: '순창군',
      cityCode: '45',
      id: 168,
    },
    {
      gugunCode: '45790',
      gugunEngName: 'Gochang-gun',
      fullName: '전라북도 고창군',
      gugunKorName: '고창군',
      cityCode: '45',
      id: 169,
    },
    {
      gugunCode: '45800',
      gugunEngName: 'Buan-gun',
      fullName: '전라북도 부안군',
      gugunKorName: '부안군',
      cityCode: '45',
      id: 170,
    },
    {
      gugunCode: '45113',
      gugunEngName: 'Deokjin-gu, Jeonju-si',
      fullName: '전라북도 전주시 덕진구',
      gugunKorName: '전주시 덕진구',
      cityCode: '45',
      id: 171,
    },
    {
      gugunCode: '45130',
      gugunEngName: 'Gunsan-si',
      fullName: '전라북도 군산시',
      gugunKorName: '군산시',
      cityCode: '45',
      id: 172,
    },
    {
      gugunCode: '45210',
      gugunEngName: 'Gimje-si',
      fullName: '전라북도 김제시',
      gugunKorName: '김제시',
      cityCode: '45',
      id: 173,
    },
    {
      gugunCode: '45140',
      gugunEngName: 'Iksan-si',
      fullName: '전라북도 익산시',
      gugunKorName: '익산시',
      cityCode: '45',
      id: 174,
    },
    {
      gugunCode: '45180',
      gugunEngName: 'Jeongeup-si',
      fullName: '전라북도 정읍시',
      gugunKorName: '정읍시',
      cityCode: '45',
      id: 175,
    },
    {
      gugunCode: '45190',
      gugunEngName: 'Namwon-si',
      fullName: '전라북도 남원시',
      gugunKorName: '남원시',
      cityCode: '45',
      id: 176,
    },
    {
      gugunCode: '45710',
      gugunEngName: 'Wanju-gun',
      fullName: '전라북도 완주군',
      gugunKorName: '완주군',
      cityCode: '45',
      id: 177,
    },
    {
      gugunCode: '45720',
      gugunEngName: 'Jinan-gun',
      fullName: '전라북도 진안군',
      gugunKorName: '진안군',
      cityCode: '45',
      id: 178,
    },
    {
      gugunCode: '45730',
      gugunEngName: 'Muju-gun',
      fullName: '전라북도 무주군',
      gugunKorName: '무주군',
      cityCode: '45',
      id: 179,
    },
    {
      gugunCode: '45740',
      gugunEngName: 'Jangsu-gun',
      fullName: '전라북도 장수군',
      gugunKorName: '장수군',
      cityCode: '45',
      id: 180,
    },
    {
      gugunCode: '46110',
      gugunEngName: 'Mokpo-si',
      fullName: '전라남도 목포시',
      gugunKorName: '목포시',
      cityCode: '46',
      id: 181,
    },
    {
      gugunCode: '46790',
      gugunEngName: 'Hwasun-gun',
      fullName: '전라남도 화순군',
      gugunKorName: '화순군',
      cityCode: '46',
      id: 182,
    },
    {
      gugunCode: '46800',
      gugunEngName: 'Jangheung-gun',
      fullName: '전라남도 장흥군',
      gugunKorName: '장흥군',
      cityCode: '46',
      id: 183,
    },
    {
      gugunCode: '46810',
      gugunEngName: 'Gangjin-gun',
      fullName: '전라남도 강진군',
      gugunKorName: '강진군',
      cityCode: '46',
      id: 184,
    },
    {
      gugunCode: '46130',
      gugunEngName: 'Yeosu-si',
      fullName: '전라남도 여수시',
      gugunKorName: '여수시',
      cityCode: '46',
      id: 185,
    },
    {
      gugunCode: '46230',
      gugunEngName: 'Gwangyang-si',
      fullName: '전라남도 광양시',
      gugunKorName: '광양시',
      cityCode: '46',
      id: 186,
    },
    {
      gugunCode: '46150',
      gugunEngName: 'Suncheon-si',
      fullName: '전라남도 순천시',
      gugunKorName: '순천시',
      cityCode: '46',
      id: 187,
    },
    {
      gugunCode: '46820',
      gugunEngName: 'Haenam-gun',
      fullName: '전라남도 해남군',
      gugunKorName: '해남군',
      cityCode: '46',
      id: 188,
    },
    {
      gugunCode: '46170',
      gugunEngName: 'Naju-si',
      fullName: '전라남도 나주시',
      gugunKorName: '나주시',
      cityCode: '46',
      id: 189,
    },
    {
      gugunCode: '46830',
      gugunEngName: 'Yeongam-gun',
      fullName: '전라남도 영암군',
      gugunKorName: '영암군',
      cityCode: '46',
      id: 190,
    },
    {
      gugunCode: '46710',
      gugunEngName: 'Damyang-gun',
      fullName: '전라남도 담양군',
      gugunKorName: '담양군',
      cityCode: '46',
      id: 191,
    },
    {
      gugunCode: '46840',
      gugunEngName: 'Muan-gun',
      fullName: '전라남도 무안군',
      gugunKorName: '무안군',
      cityCode: '46',
      id: 192,
    },
    {
      gugunCode: '46720',
      gugunEngName: 'Gokseong-gun',
      fullName: '전라남도 곡성군',
      gugunKorName: '곡성군',
      cityCode: '46',
      id: 193,
    },
    {
      gugunCode: '46860',
      gugunEngName: 'Hampyeong-gun',
      fullName: '전라남도 함평군',
      gugunKorName: '함평군',
      cityCode: '46',
      id: 194,
    },
    {
      gugunCode: '46870',
      gugunEngName: 'Yeonggwang-gun',
      fullName: '전라남도 영광군',
      gugunKorName: '영광군',
      cityCode: '46',
      id: 195,
    },
    {
      gugunCode: '46880',
      gugunEngName: 'Jangseong-gun',
      fullName: '전라남도 장성군',
      gugunKorName: '장성군',
      cityCode: '46',
      id: 196,
    },
    {
      gugunCode: '46890',
      gugunEngName: 'Wando-gun',
      fullName: '전라남도 완도군',
      gugunKorName: '완도군',
      cityCode: '46',
      id: 197,
    },
    {
      gugunCode: '46900',
      gugunEngName: 'Jindo-gun',
      fullName: '전라남도 진도군',
      gugunKorName: '진도군',
      cityCode: '46',
      id: 198,
    },
    {
      gugunCode: '46730',
      gugunEngName: 'Gurye-gun',
      fullName: '전라남도 구례군',
      gugunKorName: '구례군',
      cityCode: '46',
      id: 199,
    },
    {
      gugunCode: '46770',
      gugunEngName: 'Goheung-gun',
      fullName: '전라남도 고흥군',
      gugunKorName: '고흥군',
      cityCode: '46',
      id: 200,
    },
    {
      gugunCode: '46910',
      gugunEngName: 'Sinan-gun',
      fullName: '전라남도 신안군',
      gugunKorName: '신안군',
      cityCode: '46',
      id: 201,
    },
    {
      gugunCode: '46780',
      gugunEngName: 'Boseong-gun',
      fullName: '전라남도 보성군',
      gugunKorName: '보성군',
      cityCode: '46',
      id: 202,
    },
    {
      gugunCode: '47111',
      gugunEngName: 'Nam-gu, Pohang-si',
      fullName: '경상북도 포항시 남구',
      gugunKorName: '포항시 남구',
      cityCode: '47',
      id: 203,
    },
    {
      gugunCode: '47113',
      gugunEngName: 'Buk-gu, Pohang-si',
      fullName: '경상북도 포항시 북구',
      gugunKorName: '포항시 북구',
      cityCode: '47',
      id: 204,
    },
    {
      gugunCode: '47720',
      gugunEngName: 'Gunwi-gun',
      fullName: '경상북도 군위군',
      gugunKorName: '군위군',
      cityCode: '47',
      id: 205,
    },
    {
      gugunCode: '47730',
      gugunEngName: 'Uiseong-gun',
      fullName: '경상북도 의성군',
      gugunKorName: '의성군',
      cityCode: '47',
      id: 206,
    },
    {
      gugunCode: '47750',
      gugunEngName: 'Cheongsong-gun',
      fullName: '경상북도 청송군',
      gugunKorName: '청송군',
      cityCode: '47',
      id: 207,
    },
    {
      gugunCode: '47760',
      gugunEngName: 'Yeongyang-gun',
      fullName: '경상북도 영양군',
      gugunKorName: '영양군',
      cityCode: '47',
      id: 208,
    },
    {
      gugunCode: '47770',
      gugunEngName: 'Yeongdeok-gun',
      fullName: '경상북도 영덕군',
      gugunKorName: '영덕군',
      cityCode: '47',
      id: 209,
    },
    {
      gugunCode: '47820',
      gugunEngName: 'Cheongdo-gun',
      fullName: '경상북도 청도군',
      gugunKorName: '청도군',
      cityCode: '47',
      id: 210,
    },
    {
      gugunCode: '47830',
      gugunEngName: 'Goryeong-gun',
      fullName: '경상북도 고령군',
      gugunKorName: '고령군',
      cityCode: '47',
      id: 211,
    },
    {
      gugunCode: '47840',
      gugunEngName: 'Seongju-gun',
      fullName: '경상북도 성주군',
      gugunKorName: '성주군',
      cityCode: '47',
      id: 212,
    },
    {
      gugunCode: '47850',
      gugunEngName: 'Chilgok-gun',
      fullName: '경상북도 칠곡군',
      gugunKorName: '칠곡군',
      cityCode: '47',
      id: 213,
    },
    {
      gugunCode: '47900',
      gugunEngName: 'Yecheon-gun',
      fullName: '경상북도 예천군',
      gugunKorName: '예천군',
      cityCode: '47',
      id: 214,
    },
    {
      gugunCode: '47920',
      gugunEngName: 'Bonghwa-gun',
      fullName: '경상북도 봉화군',
      gugunKorName: '봉화군',
      cityCode: '47',
      id: 215,
    },
    {
      gugunCode: '47930',
      gugunEngName: 'Uljin-gun',
      fullName: '경상북도 울진군',
      gugunKorName: '울진군',
      cityCode: '47',
      id: 216,
    },
    {
      gugunCode: '47940',
      gugunEngName: 'Ulleung-gun',
      fullName: '경상북도 울릉군',
      gugunKorName: '울릉군',
      cityCode: '47',
      id: 217,
    },
    {
      gugunCode: '47130',
      gugunEngName: 'Gyeongju-si',
      fullName: '경상북도 경주시',
      gugunKorName: '경주시',
      cityCode: '47',
      id: 218,
    },
    {
      gugunCode: '47210',
      gugunEngName: 'Yeongju-si',
      fullName: '경상북도 영주시',
      gugunKorName: '영주시',
      cityCode: '47',
      id: 219,
    },
    {
      gugunCode: '47230',
      gugunEngName: 'Yeongcheon-si',
      fullName: '경상북도 영천시',
      gugunKorName: '영천시',
      cityCode: '47',
      id: 220,
    },
    {
      gugunCode: '47150',
      gugunEngName: 'Gimcheon-si',
      fullName: '경상북도 김천시',
      gugunKorName: '김천시',
      cityCode: '47',
      id: 221,
    },
    {
      gugunCode: '47170',
      gugunEngName: 'Andong-si',
      fullName: '경상북도 안동시',
      gugunKorName: '안동시',
      cityCode: '47',
      id: 222,
    },
    {
      gugunCode: '47190',
      gugunEngName: 'Gumi-si',
      fullName: '경상북도 구미시',
      gugunKorName: '구미시',
      cityCode: '47',
      id: 223,
    },
    {
      gugunCode: '47250',
      gugunEngName: 'Sangju-si',
      fullName: '경상북도 상주시',
      gugunKorName: '상주시',
      cityCode: '47',
      id: 224,
    },
    {
      gugunCode: '47280',
      gugunEngName: 'Mungyeong-si',
      fullName: '경상북도 문경시',
      gugunKorName: '문경시',
      cityCode: '47',
      id: 225,
    },
    {
      gugunCode: '47290',
      gugunEngName: 'Gyeongsan-si',
      fullName: '경상북도 경산시',
      gugunKorName: '경산시',
      cityCode: '47',
      id: 226,
    },
    {
      gugunCode: '48121',
      gugunEngName: 'Uichang-gu, Changwon-si',
      fullName: '경상남도 창원시 의창구',
      gugunKorName: '창원시 의창구',
      cityCode: '48',
      id: 227,
    },
    {
      gugunCode: '48270',
      gugunEngName: 'Miryang-si',
      fullName: '경상남도 밀양시',
      gugunKorName: '밀양시',
      cityCode: '48',
      id: 228,
    },
    {
      gugunCode: '48310',
      gugunEngName: 'Geoje-si',
      fullName: '경상남도 거제시',
      gugunKorName: '거제시',
      cityCode: '48',
      id: 229,
    },
    {
      gugunCode: '48330',
      gugunEngName: 'Yangsan-si',
      fullName: '경상남도 양산시',
      gugunKorName: '양산시',
      cityCode: '48',
      id: 230,
    },
    {
      gugunCode: '48720',
      gugunEngName: 'Uiryeong-gun',
      fullName: '경상남도 의령군',
      gugunKorName: '의령군',
      cityCode: '48',
      id: 231,
    },
    {
      gugunCode: '48730',
      gugunEngName: 'Haman-gun',
      fullName: '경상남도 함안군',
      gugunKorName: '함안군',
      cityCode: '48',
      id: 232,
    },
    {
      gugunCode: '48740',
      gugunEngName: 'Changnyeong-gun',
      fullName: '경상남도 창녕군',
      gugunKorName: '창녕군',
      cityCode: '48',
      id: 233,
    },
    {
      gugunCode: '48820',
      gugunEngName: 'Goseong-gun',
      fullName: '경상남도 고성군',
      gugunKorName: '고성군',
      cityCode: '48',
      id: 234,
    },
    {
      gugunCode: '48840',
      gugunEngName: 'Namhae-gun',
      fullName: '경상남도 남해군',
      gugunKorName: '남해군',
      cityCode: '48',
      id: 235,
    },
    {
      gugunCode: '48850',
      gugunEngName: 'Hadong-gun',
      fullName: '경상남도 하동군',
      gugunKorName: '하동군',
      cityCode: '48',
      id: 236,
    },
    {
      gugunCode: '48860',
      gugunEngName: 'Sancheong-gun',
      fullName: '경상남도 산청군',
      gugunKorName: '산청군',
      cityCode: '48',
      id: 237,
    },
    {
      gugunCode: '48870',
      gugunEngName: 'Hamyang-gun',
      fullName: '경상남도 함양군',
      gugunKorName: '함양군',
      cityCode: '48',
      id: 238,
    },
    {
      gugunCode: '48880',
      gugunEngName: 'Geochang-gun',
      fullName: '경상남도 거창군',
      gugunKorName: '거창군',
      cityCode: '48',
      id: 239,
    },
    {
      gugunCode: '48890',
      gugunEngName: 'Hapcheon-gun',
      fullName: '경상남도 합천군',
      gugunKorName: '합천군',
      cityCode: '48',
      id: 240,
    },
    {
      gugunCode: '48123',
      gugunEngName: 'Seongsan-gu, Changwon-si',
      fullName: '경상남도 창원시 성산구',
      gugunKorName: '창원시 성산구',
      cityCode: '48',
      id: 241,
    },
    {
      gugunCode: '48220',
      gugunEngName: 'Tongyeong-si',
      fullName: '경상남도 통영시',
      gugunKorName: '통영시',
      cityCode: '48',
      id: 242,
    },
    {
      gugunCode: '48125',
      gugunEngName: 'Masanhappo-gu, Changwon-si',
      fullName: '경상남도 창원시 마산합포구',
      gugunKorName: '창원시 마산합포구',
      cityCode: '48',
      id: 243,
    },
    {
      gugunCode: '48127',
      gugunEngName: 'Masanhoewon-gu, Changwon-si',
      fullName: '경상남도 창원시 마산회원구',
      gugunKorName: '창원시 마산회원구',
      cityCode: '48',
      id: 244,
    },
    {
      gugunCode: '48129',
      gugunEngName: 'Jinhae-gu, Changwon-si',
      fullName: '경상남도 창원시 진해구',
      gugunKorName: '창원시 진해구',
      cityCode: '48',
      id: 245,
    },
    {
      gugunCode: '48170',
      gugunEngName: 'Jinju-si',
      fullName: '경상남도 진주시',
      gugunKorName: '진주시',
      cityCode: '48',
      id: 246,
    },
    {
      gugunCode: '48240',
      gugunEngName: 'Sacheon-si',
      fullName: '경상남도 사천시',
      gugunKorName: '사천시',
      cityCode: '48',
      id: 247,
    },
    {
      gugunCode: '48250',
      gugunEngName: 'Gimhae-si',
      fullName: '경상남도 김해시',
      gugunKorName: '김해시',
      cityCode: '48',
      id: 248,
    },
    {
      gugunCode: '50110',
      gugunEngName: 'Jeju-si',
      fullName: '제주특별자치도 제주시',
      gugunKorName: '제주시',
      cityCode: '50',
      id: 249,
    },
    {
      gugunCode: '50130',
      gugunEngName: 'Seogwipo-si',
      fullName: '제주특별자치도 서귀포시',
      gugunKorName: '서귀포시',
      cityCode: '50',
      id: 250,
    },
  ],
};
